spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/marketplace"
    username: postgres
    password: 452389
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: vitaloverzyn34@gmail.com
    password: buau shfj xpqm xdii
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  elasticsearch:
    uris: "http://localhost:9200"
jwt:
  token:
    secret: sl8d45b4o2h35g243ilk7fdsgsfdljkhgfldkgh94837wyhglkfdjshgsd98f7og643gldujfhlafsdkhf43q287r3t26kdgzjfds
    expiration:
      time: 3000000
  refresh:
    token:
      expiration:
        time: 2629743000
  password:
    reset:
      token:
        expiration:
          time: 1800000


