spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/marketplace"
    username: postgres
    password: 452389
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update


jwt:
  token:
    secret: :LKJOSDI987sd98g7fdgjkh45lkj243hlk34h25gk234h5guj234hdsuigyf87dsgysfdghkljfd8gs59dgxcv6bxcv6by78xyiolzu7
    expiration:
      time: 3600000