spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/marketplace"
    username: postgres
    password: 452389
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: vitaloverzyn34@gmail.com
    password: teoj awfa pzsg ybuf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  elasticsearch:
    uris: "http://localhost:9200"

  servlet:
    multipart:
      max-file-size: "5MB"
      max-request-size: "5MB"

sentry:
  dsn: https://78319190a391ed170840ac8023e4ab6c@o4507282571067392.ingest.de.sentry.io/4507282575720528

jwt:
  token:
    secret: sl8d45b4o2h35g243ilk7fdsgsfdljkhgfldkgh94837wyhglkfdjshgsd98f7og643gldujfhlafsdkhf43q287r3t26kdgzjfds
    expiration:
      time: 3000000
  refresh:
    token:
      expiration:
        time: 2629743000
  password:
    reset:
      token:
        expiration:
          time: 1800000

aws:
  access:
    key: AKIA47CRXS44VK5LTU45
  secret:
    key: 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
  region: us-east-1
  product:
    images:
      bucket:
        name: "product-images-marketplace"
    review:
      media-content:
        bucket-name: "product-reviews-marketplace"

