spring:
  datasource:
    url: #put your postgresql url to database
    username: #put your postgresql username
    password: #put your postgresql password
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: #put your email
    password:  #put your email application password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  elasticsearch:
    uris: "http://localhost:9200"

  servlet:
    multipart:
      max-file-size: "200MB"
      max-request-size: "200MB"

sentry:
  dsn: #put your sentry dsn link

jwt:
  token:
    secret: sl8d45b4o2h35g243ilk7fdsgsfdljkhgfldkgh94837wyhglkfdjshgsd98f7og643gldujfhlafsdkhf43q287r3t26kdgzjfds
    expiration:
      time: 3000000
  refresh:
    token:
      expiration:
        time: 2629743000
  password:
    reset:
      token:
        expiration:
          time: 1800000

aws:
  access:
    key: #put your aws access key
  secret:
    key: #put your aws secret key
  region: #put your aws region
  product:
    images:
      bucket:
        name: #put your product-images bucket name
    review:
      media-content:
        bucket-name: #put your media-review-content bucket name

